

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - app_network
      - pr_preview_network   
    ports:
      - "5672:5672"
      - "15672:15672"
  

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env
  
    volumes:
      - .:/code
    depends_on:
      - rabbitmq

networks:
  app_network:
    driver: bridge
  pr_preview_network:
    driver: bridge